export const types = {
    normal: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: .5,
        ghost: 0,
        dragon: 1,
        dark: 1,
        steel: .5,
        fairy: 1 // complete
    },
    fire: {
        normal: 1,
        fire: .5,
        water: .5,
        electric: 1,
        grass: 2,
        ice: 2,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 2,
        rock: .5,
        ghost: 1,
        dragon: .5,
        dark: 1,
        steel: 2,
        fairy: 1 //complete
    },
    water: {
        normal: 1,
        fire: 2,
        water: .5,
        electric: 1,
        grass: .5,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 2,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 2,
        ghost: 1,
        dragon: .5,
        dark: 1,
        steel: 1,
        fairy: 1 //complete

    },
    electric: {
        normal: 1,
        fire: 1,
        water: 2,
        electric: .5,
        grass: .5,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 0,
        flying: 2,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: .5,
        dark: 1,
        steel: 1,
        fairy: 1 //complete
    },
    grass: {
        normal: 1,
        fire: .5,
        water: 2,
        electric: 1,
        grass: .5,
        ice: 1,
        fighting: 1,
        poison: .5,
        ground: 2,
        flying: .5,
        psychic: 1,
        bug: .5,
        rock: 2,
        ghost: 1,
        dragon: .5,
        dark: 1,
        steel: .5,
        fairy: 1 // completed
    },
    ice: {
        normal: 1,
        fire: .5,
        water: .5,
        electric: 1,
        grass: 2,
        ice: .5,
        fighting: 1,
        poison: 1,
        ground: 2,
        flying: 2,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 1,
        steel: .5,
        fairy: 1 // completed
    },
    fighting: {
        normal: 2,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 2,
        fighting: 1,
        poison: .5,
        ground: 1,
        flying: .5,
        psychic: .5,
        bug: .5,
        rock: 2,
        ghost: 0,
        dragon: 1,
        dark: 2,
        steel: 2,
        fairy: .5 // completed
    },
    poison: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 2,
        ice: 1,
        fighting: 1,
        poison: .5,
        ground: .5,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: .5,
        ghost: .5,
        dragon: 1,
        dark: 1,
        steel: 0,
        fairy: 2 // completed
    },
    ground: {
        normal: 1,
        fire: 2,
        water: 1,
        electric: 2,
        grass: .5,
        ice: 1,
        fighting: 1,
        poison: 2,
        ground: 1,
        flying: 0,
        psychic: 1,
        bug: .5,
        rock: 2,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: 2,
        fairy: 1 // completed
    },
    flying: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: .5,
        grass: 2,
        ice: 1,
        fighting: 2,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 2,
        rock: .5,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: .5,
        fairy: 1 // completed
    },
    psychic: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 2,
        poison: 2,
        ground: 1,
        flying: 1,
        psychic: .5,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 1,
        dark: 0,
        steel: .5,
        fairy: 1 // completed
    },
    bug: {
        normal: 1,
        fire: .5,
        water: 1,
        electric: 1,
        grass: 2,
        ice: 1,
        fighting: .5,
        poison: .5,
        ground: 1,
        flying: .5,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: .5,
        dragon: 1,
        dark: 2,
        steel: .5,
        fairy: .5 // completed
    },
    rock: {
        normal: 1,
        fire: 2,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 2,
        fighting: .5,
        poison: 1,
        ground: .5,
        flying: 2,
        psychic: 1,
        bug: 2,
        rock: 1,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: .5,
        fairy: 1 // completed
    },
    ghost: {
        normal: 0,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 2,
        dragon: 1,
        dark: .5,
        steel: 1,
        fairy: 1 // completed
    },
    dragon: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 1,
        steel: .5,
        fairy: 0 // completed
    },
    dark: {
        normal: 1,
        fire: 1,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: .5,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 2,
        bug: 1,
        rock: 1,
        ghost: 2,
        dragon: 1,
        dark: .5,
        steel: 1,
        fairy: .5 // completed
    },
    steel: {
        normal: 1,
        fire: .5,
        water: .5,
        electric: .5,
        grass: 1,
        ice: 2,
        fighting: 1,
        poison: 1,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 2,
        ghost: 1,
        dragon: 1,
        dark: 1,
        steel: .5,
        fairy: 2
    },
    fairy: {
        normal: 1,
        fire: .5,
        water: 1,
        electric: 1,
        grass: 1,
        ice: 1,
        fighting: 2,
        poison: .5,
        ground: 1,
        flying: 1,
        psychic: 1,
        bug: 1,
        rock: 1,
        ghost: 1,
        dragon: 2,
        dark: 2,
        steel: .5,
        fairy: 1 // completed
    }
}

export function typeChart() {
    let title = "          NOR FIR WAT ELE GRA ICE FIG POI GRO FLY PSY BUG ROC GHO DRA DAR STE FAI"
    console.log(title)
    for( let row in types ){
        let header = row.toUpperCase();
        while(header.length < 10){
            header +=" "
        }
        const off = types[row]
        for (let col in off){
            let str = off[col]==1?" - ":""+off[col]
            while(str.length<3){
                str+=" "
            }
            header +=str+" "
        }
        console.log(header)
    }
}